AWSTemplateFormatVersion: 2010-09-09
Description: Staging environment template for the homework.

Parameters:
  WebServerImage:
    Type: AWS::EC2::Image::Id
    Description: Custom AMI ID for the web server instance
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: SubnetId of an existing subnet (for the primary network) in your
      Virtual Private Cloud (VPC)

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref WebServerImage
      InstanceType: t2.micro
      # IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "CARELLE POTATOES" > /var/www/html/index.html
      Tags:
        -
          Key: Name
          Value: !Sub "${AWS::StackName}-WebServer"
        - 
          Key: Environment
          Value: Staging

  # InstanceProfile:
  #   Type: AWS::IAM::InstanceProfile
  #   Properties: 
  #     Roles: 
  #       - !Ref WebServerRoleName

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for web servers 
      SecurityGroupIngress: 
        - 
          IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"

Outputs:
  WebServerDnsName:
    Value: !GetAtt WebServerInstance.PublicDnsName
    Description: Public DNS name of the web server instance
